"""add 'refresh_token' and 'refresh_token_expires' columns to users table

Revision ID: 4cd16bc8f097
Revises: 8cf1e0cc57ff
Create Date: 2024-02-20 15:04:38.880717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cd16bc8f097'
down_revision: Union[str, None] = '8cf1e0cc57ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('refresh_token_expires', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_token_expires')
    op.drop_column('users', 'refresh_token')
    # ### end Alembic commands ###
