"""adds activation code and removes phone number from users table

Revision ID: 666700af93c2
Revises: 20ae56dd5f9a
Create Date: 2024-02-07 18:48:32.394065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '666700af93c2'
down_revision: Union[str, None] = '20ae56dd5f9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('activation_code', sa.String(), server_default=sa.text('NULL'), nullable=True))
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'activation_code')
    # ### end Alembic commands ###
