"""add default admin to table

Revision ID: 6d0a20636254
Revises: af780f9a0f09
Create Date: 2024-02-22 15:49:24.263132

"""

import os
from typing import Sequence, Union

from alembic import op

from passlib.context import CryptContext

# revision identifiers, used by Alembic.
revision: str = "6d0a20636254"
down_revision: Union[str, None] = "af780f9a0f09"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")

    email = os.environ.get("ADMIN_EMAIL")
    password = os.environ.get("ADMIN_PASSWORD")

    password_hash = pwd_context.hash(password)
    op.execute(
        f"INSERT INTO users (email, password, is_active, is_admin) VALUES ('{email}', '{password_hash}', True, True)"

    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
